# The URL the site will be built for
base_url = "https://klau.si"

# Output directory for the built site
output_dir = "docs"

title = "Klausi's Weblog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "even"

taxonomies = [
    # You can enable/disable RSS
    { name = "tags", feed = true },
]

generate_feeds = true
feed_filenames = ["rss.xml"]
feed_limit = 20
author = "Klaus Purer"

[markdown.highlighting]
theme = "github-dark"

[extra]
# Put all your custom variables here

even_title = "Klausi's Weblog"

even_menu = [
    { url = "$BASE_URL", name = "Home" },
    { url = "$BASE_URL/tags/speaking", name = "Speaking" },
    { url = "$BASE_URL/tags", name = "Categories" },
    { url = "$BASE_URL/rss.xml", name = "RSS" },
]
